# Generated by Django 5.2.16 on 2026-07-16 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='client_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='destination',
            name='client_secret',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='destination',
            name='refresh_token',
            field=models.TextField(blank=True, default=''),
        ),
    ]
