# Generated by Django 5.2.16 on 2026-07-16 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0002_destination_client_id_destination_client_secret_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='YouTubeAppConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=255)),
                ('client_secret', models.TextField()),
                ('redirect_uri', models.URLField()),
            ],
        ),
    ]
