# Generated by Django 5.2.16 on 2026-08-07 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0004_uploadtemplate_delete_youtubeappconfig_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadtemplate',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
