# Generated by Django 5.2.16 on 2026-08-07 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0005_uploadtemplate_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='token_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
