# Generated by Django 5.2.16 on 2026-08-10 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0006_destination_token_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='data_access_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
