# Generated by Django 5.2.16 on 2026-08-03 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('youtube', 'YouTube'), ('facebook', 'Facebook'), ('tiktok', 'TikTok'), ('instagram', 'Instagram')], help_text='The platform this config belongs to.', max_length=50, unique=True)),
                ('client_id', models.CharField(blank=True, help_text='API Client ID or App ID', max_length=255)),
                ('client_secret', models.TextField(blank=True, help_text='API Client Secret or App Secret')),
                ('redirect_uri', models.URLField(blank=True, help_text='OAuth Redirect URI if required')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
