# Generated by Django 5.2.16 on 2026-08-03 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerconfig',
            name='additional_settings',
            field=models.JSONField(blank=True, default=dict, help_text='Extra config specific to the provider (e.g., API keys, Page IDs, specific scopes) in JSON format.'),
        ),
    ]
