# Generated by Django 5.2.16 on 2026-08-03 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0002_providerconfig_additional_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app_id', models.CharField(help_text='Facebook App ID', max_length=255)),
                ('app_secret', models.TextField(help_text='Facebook App Secret')),
                ('redirect_uri', models.URLField(help_text='Facebook OAuth Redirect URI')),
            ],
            options={
                'verbose_name': 'Facebook Configuration',
                'verbose_name_plural': 'Facebook Configurations',
            },
        ),
        migrations.CreateModel(
            name='TikTokConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_key', models.CharField(help_text='TikTok Client Key', max_length=255)),
                ('client_secret', models.TextField(help_text='TikTok Client Secret')),
                ('redirect_uri', models.URLField(help_text='TikTok Redirect URI')),
            ],
            options={
                'verbose_name': 'TikTok Configuration',
                'verbose_name_plural': 'TikTok Configurations',
            },
        ),
        migrations.CreateModel(
            name='YouTubeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_id', models.CharField(help_text='Google OAuth Client ID', max_length=255)),
                ('client_secret', models.TextField(help_text='Google OAuth Client Secret')),
                ('redirect_uri', models.URLField(help_text='Google OAuth Redirect URI')),
            ],
            options={
                'verbose_name': 'YouTube Configuration',
                'verbose_name_plural': 'YouTube Configurations',
            },
        ),
        migrations.DeleteModel(
            name='ProviderConfig',
        ),
    ]
