# Generated by Django 5.2.16 on 2026-08-04 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0004_remove_tiktokconfig'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FacebookConfig',
        ),
    ]
