# Generated by Django 5.2.16 on 2026-08-06 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0005_remove_facebookconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_id', models.CharField(help_text='Facebook App ID', max_length=255)),
                ('client_secret', models.TextField(help_text='Facebook App Secret')),
                ('redirect_uri', models.URLField(help_text='Facebook OAuth Redirect URI')),
            ],
            options={
                'verbose_name': 'Facebook Configuration',
                'verbose_name_plural': 'Facebook Configurations',
            },
        ),
    ]
